Fix invalid cloud-config schema in pxe user data
cloud-init on the BFB installer is complaining about our
cloud-config.txt:

```
schema.py[WARNING]: cloud-config failed schema validation! You may run 'sudo cloud-init schema --system' to check the details.
```

With the schema validator showing this on an example rendered
cloud-config.txt:

```
cloud-init schema --system
Invalid user-data /var/lib/cloud/instances/nocloud/cloud-config.txt
Error: Cloud config schema errors: debug: Additional properties are not allowed ('debug' was unexpected)

Error: Invalid schema: user-data
```

It's not causing any actual failures, but it's a kinda scary-looking
warning, so it's worth fixing. So, drop the debug section... I'm not
sure it was ever valid, the closest I found to this is from an old
version of cloud-init documenting [the cc_debug module][0]. With config
gone, the schema validator now passes.

[0]: https://docs.cloud-init.io/en/0.7.8/topics/modules.html#debug